# Lari Traders Custom Backup Config
drive-folder-id=13s8_LBLghhIh8IlhFFE6GIomKIdxp1qq
apps-script-url=https://script.google.com/macros/s/AKfycbz3XlDO_nLbpq8iBdMLlVY8SnDD39Jg0XfziWDiGv-Bk1D-itsQq1PLFK2NnnV6cm27ww/exec
