# Production Profile Configuration
# SECURITY NOTE: Hamesha dedicated limited-privilege database user profile utilize karein.
# SECURITY NOTE: Remote PostgreSQL integration ke case me "?sslmode=require" append karein.
spring.datasource.url=jdbc:postgresql://localhost:5432/fmcg_shop_prod
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
logging.level.com.shop=WARN
server.port=8086


# Swagger — DISABLED in production
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
