ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS first_reminder_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS manager_alerted BOOLEAN DEFAULT FALSE;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS reconciliation_status VARCHAR(50) DEFAULT 'PENDING';
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS customer_confirmed BOOLEAN DEFAULT FALSE;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS customer_confirmed_at TIMESTAMP;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_source VARCHAR(50);

